// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';






var d1 = {
  dx: 20,
  dy: 0
};

var d2 = {
  dx: 0,
  dy: 20
};

var d3 = {
  dx: -20,
  dy: 0
};

var d4 = {
  dx: 0,
  dy: -20
};

var d0 = {
  dx: 0,
  dy: 0
};

var ds = [
  d1,
  d2,
  d3,
  d4
];

var sn1 = {
  sx: 120,
  sy: 100,
  dir: d0,
  trail: /* [] */0,
  size: 64,
  len: 0,
  twCl1: "#2358",
  twCl2: "#46b2"
};

var sn2 = {
  sx: 460,
  sy: 320,
  dir: d0,
  trail: /* [] */0,
  size: 64,
  len: 0,
  twCl1: "#5238",
  twCl2: "#b462"
};

var sn3 = {
  sx: 240,
  sy: 220,
  dir: d0,
  trail: /* [] */0,
  size: 64,
  len: 0,
  twCl1: "#2538",
  twCl2: "#4b62"
};

var canvas = document.getElementById("c1");

var ctx = canvas.getContext("2d");

var sn_lst = {
  contents: {
    hd: sn1,
    tl: {
      hd: sn2,
      tl: {
        hd: sn3,
        tl: /* [] */0
      }
    }
  }
};

var twrs_lst = {
  contents: /* [] */0
};

var rand = Random.$$int;

function rnd(a, b) {
  return a + Random.$$int((1 + b | 0) - a | 0) | 0;
}

function push(lst, elem) {
  lst.contents = {
    hd: elem,
    tl: lst.contents
  };
  
}

function shift(lst) {
  if (lst) {
    return lst.tl;
  } else {
    return lst;
  }
}

function putTwr(sn) {
  return push(twrs_lst, {
              tx: sn.sx,
              ty: sn.sy,
              lim: rnd(320, 3200),
              cl1: sn.twCl1,
              cl2: sn.twCl2
            });
}

function swtchSn(param) {
  var match = sn_lst.contents;
  if (!match) {
    return ;
  }
  var match$1 = match.tl;
  if (!match$1) {
    return ;
  }
  var match$2 = match$1.tl;
  if (match$2 && !match$2.tl) {
    sn_lst.contents = {
      hd: match$1.hd,
      tl: {
        hd: match$2.hd,
        tl: {
          hd: match.hd,
          tl: /* [] */0
        }
      }
    };
    return ;
  }
  
}

var cShp1 = new Path2D();

cShp1.arc(10.0, 10.0, 9, 0, 6.2830);

function drawBg(param) {
  ctx.fillStyle = "#223";
  ctx.fillRect(0, 0, 780, 500);
  
}

function drawRect(param, cl) {
  ctx.fillStyle = cl;
  ctx.fillRect(param[0], param[1], 20, 20);
  
}

function drawSn(sn, cl) {
  return drawRect([
              sn.sx,
              sn.sy
            ], cl);
}

function drawTxt(param, txt, cl) {
  ctx.fillStyle = cl;
  ctx.font = "15px mono";
  ctx.fillText(txt, param[0], param[1]);
  
}

function stepSn(sn) {
  var d = sn.dir;
  var match;
  if (Caml_obj.caml_notequal(d, d0)) {
    var trail_0 = {
      dx: sn.sx,
      dy: sn.sy
    };
    var trail_1 = sn.trail;
    var trail = {
      hd: trail_0,
      tl: trail_1
    };
    var len = sn.len + 1 | 0;
    var trail$1 = sn.len >= sn.size ? shift(sn.trail) : trail;
    match = [
      trail$1,
      len
    ];
  } else {
    match = [
      sn.trail,
      sn.len
    ];
  }
  var sx = sn.sx + d.dx | 0;
  var sy = sn.sy + d.dy | 0;
  return {
          sx: sx,
          sy: sy,
          dir: sn.dir,
          trail: match[0],
          size: sn.size,
          len: match[1],
          twCl1: sn.twCl1,
          twCl2: sn.twCl2
        };
}

function rndTake(arr) {
  var n = arr.length;
  return Caml_array.get(arr, Random.$$int(n));
}

function mvTwrs(param) {
  twrs_lst.contents = List.map((function (twr) {
          if (Random.$$float(1.0) >= 0.01) {
            return twr;
          }
          var d = rndTake(ds);
          var tx = twr.tx + d.dx | 0;
          var ty = twr.ty + d.dy | 0;
          return {
                  tx: tx,
                  ty: ty,
                  lim: twr.lim,
                  cl1: twr.cl1,
                  cl2: twr.cl2
                };
        }), twrs_lst.contents);
  
}

function stepTwrs(param) {
  twrs_lst.contents = List.map((function (twr) {
          var lim = twr.lim - 1 | 0;
          return {
                  tx: twr.tx,
                  ty: twr.ty,
                  lim: lim,
                  cl1: twr.cl1,
                  cl2: twr.cl2
                };
        }), twrs_lst.contents);
  twrs_lst.contents = List.filter(function (twr) {
          return twr.lim >= 0;
        })(twrs_lst.contents);
  return mvTwrs(undefined);
}

function step_f(param) {
  var sn1$1 = stepSn(sn1);
  var sn2$1 = stepSn(sn2);
  var sn3$1 = stepSn(sn3);
  sn_lst.contents = {
    hd: sn1$1,
    tl: {
      hd: sn2$1,
      tl: {
        hd: sn3$1,
        tl: /* [] */0
      }
    }
  };
  stepTwrs(undefined);
  
}

function drawShp(shp, param, cl) {
  var y = param[1];
  var x = param[0];
  ctx.lineWidth = 4.2;
  ctx.strokeStyle = cl;
  ctx.translate(x, y);
  ctx.stroke(shp);
  ctx.translate(-x | 0, -y | 0);
  
}

function drawTwr(tw) {
  ctx.fillStyle = tw.cl1;
  ctx.fillRect(tw.tx - 5 | 0, tw.ty - 5 | 0, 30, 30);
  return drawShp(cShp1, [
              tw.tx,
              tw.ty
            ], tw.cl2);
}

function setId(param) {
  ctx.setTransform(1.0, 0.0, 0.0, 1.0, 0.0, 0.0);
  
}

function floor(id) {
  return id;
}

function mvView(param) {
  setId(undefined);
  ctx.translate(0, 0);
  
}

function draw_f(param) {
  setId(undefined);
  drawBg(undefined);
  mvView(undefined);
  List.iter((function (d) {
          return drawRect([
                      d.dx,
                      d.dy
                    ], "#8888");
        }), /* [] */0);
  List.iter((function (d) {
          return drawRect([
                      d.dx,
                      d.dy
                    ], "#8888");
        }), /* [] */0);
  List.iter((function (d) {
          return drawRect([
                      d.dx,
                      d.dy
                    ], "#8888");
        }), /* [] */0);
  List.iter(drawTwr, twrs_lst.contents);
  drawSn(sn1, "#ddd");
  drawSn(sn2, "#888");
  drawSn(sn3, "#888");
  
}

function animate_loop(param) {
  draw_f(undefined);
  return step_f(undefined);
}

setInterval(animate_loop, 200);

function setd(sn, d) {
  var dir = Caml_obj.caml_equal(sn.dir, d1) && Caml_obj.caml_equal(d, d3) || Caml_obj.caml_equal(sn.dir, d3) && Caml_obj.caml_equal(d, d1) || Caml_obj.caml_equal(sn.dir, d2) && Caml_obj.caml_equal(d, d4) || Caml_obj.caml_equal(sn.dir, d4) && Caml_obj.caml_equal(d, d2) ? d0 : d;
  return {
          sx: sn.sx,
          sy: sn.sy,
          dir: dir,
          trail: sn.trail,
          size: sn.size,
          len: sn.len,
          twCl1: sn.twCl1,
          twCl2: sn.twCl2
        };
}

function setd$1(d) {
  var match = sn_lst.contents;
  if (!match) {
    return ;
  }
  var match$1 = match.tl;
  if (!match$1) {
    return ;
  }
  var match$2 = match$1.tl;
  if (!match$2) {
    return ;
  }
  if (match$2.tl) {
    return ;
  }
  var sn1 = setd(match.hd, d);
  sn_lst.contents = {
    hd: sn1,
    tl: {
      hd: match$1.hd,
      tl: {
        hd: match$2.hd,
        tl: /* [] */0
      }
    }
  };
  
}

function key_event(key_change, ev) {
  var match = ev.keyCode;
  if (!key_change) {
    switch (match) {
      case 37 :
          setd$1(d3);
          break;
      case 38 :
          setd$1(d4);
          break;
      case 39 :
          setd$1(d1);
          break;
      case 40 :
          setd$1(d2);
          break;
      default:
        
    }
  }
  var match$1 = ev.key;
  if (key_change) {
    return ;
  }
  switch (match$1) {
    case "a" :
        putTwr(sn1);
        return ;
    case " " :
    case "p" :
        setd$1(d0);
        return ;
    case "s" :
        swtchSn(undefined);
        return ;
    default:
      return ;
  }
}

window.addEventListener("keydown", (function (param) {
        return key_event(/* KeyDown */0, param);
      }), true);

window.addEventListener("keyup", (function (param) {
        return key_event(/* KeyUp */1, param);
      }), true);

var w = 780;

var h = 500;









































/* canvas Not a pure module */
